# This is composite action for handling cloning of nrf sources.
# Uses checkout action and west update command.

name: 'checkout and west update'
description: 'checkout sources and runs west update'
inputs:
    git-fetch-depth:
      required: false
      type: string
      default: 1
      description: 'git fetch depth passed to checkout action.'
    git-ref:
      required: false
      default: ''
      type: string
      description: 'git branch, tag or SHA passed to checkout action.'
    rebase:
      required: false
      default: 'false'
      type: string
      description: 'If true, perform a git rebase after checkout. Effective only in PR workflows.'
    path:
      required: false
      default: 'ncs/nrf'
      description: 'Path passed to checkout action.'
    west-token:
      required: false
      default: ''
      type: string
      description: 'Token used during the west update.'
    west-update-args:
      type: string
      required: false
      default: '--narrow -o=--depth=1'
      description: 'Arguments for west update command.'
    manifest-file-path:
      type: string
      required: false
      default: ''
      description: 'If set, passed to west init as --manifest-file=<manifest-file-path>.'


runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
      with:
        ref: ${{ inputs.git-ref }}
        path: ${{ inputs.path }}
        fetch-depth: ${{ inputs.git-fetch-depth }}
        persist-credentials: false

    - name: set git config
      shell: bash
      run: |
        git config --global user.email "pylon@nordicsemi.no"
        git config --global user.name "Nordic Builder"

    - name: Set git credentials
      if: ${{ inputs.west-token != '' }}
      env:
        WEST_TOKEN: ${{ inputs.west-token }}
      shell: bash
      run: |
        git config --global credential.helper ""
        git config --global --add credential.helper store
        echo "https://x-access-token:${WEST_TOKEN}@github.com" >> ~/.git-credentials

    - name: Rebase PR
      if: ${{ inputs.rebase == 'true' && github.event_name == 'pull_request' }}
      working-directory: ${{ inputs.path }}
      env:
        BASE_REF: ${{ github.base_ref }}
      shell: bash
      run: |
        git fetch origin "$BASE_REF"
        git rebase "origin/$BASE_REF"

    - name: West update
      env:
        WEST_UPDATE_ARGS: ${{ inputs.west-update-args }}
        MANIFEST_FILE_PATH: ${{ inputs.manifest-file-path }}
      working-directory: ${{ inputs.path }}
      shell: bash
      run: |
        pip3 install west
        WEST_INIT_ARGS=""
        if [ -n "$MANIFEST_FILE_PATH" ]; then
          WEST_INIT_ARGS="--manifest-file=$MANIFEST_FILE_PATH"
        fi
        west init ${WEST_INIT_ARGS:+"$WEST_INIT_ARGS"} --local .
        west update $WEST_UPDATE_ARGS

    - name: Remove git credentials
      if: ${{ always() && inputs.west-token != '' }}
      shell: bash
      run: |
        rm -f ~/.git-credentials
